"""
ships nationality
"""
import typing
import math

COUNTRY_MAPPING = {
    201: ("AL", "Albanees"),
    202: ("AD", "Andorrees"),
    203: ("AT", "oostenrijks"),
    204: ("PT", "Portugees"),
    205: ("BE", "Belgies"),
    206: ("BY", "Belarusisch"),
    207: ("BG", "Bulgarees"),
    208: ("VA", "Vatican"),
    209: ("CY", "Cypriotisch"),
    210: ("CY", "Cypriotisch"),
    211: ("DE", "Duits"),
    212: ("CY", "Cypriotisch"),
    213: ("GE", "Georgia"),
    214: ("MD", "Moldova"),
    215: ("MT", "Maltees"),
    216: ("AM", "Armeneens"),
    218: ("DE", "Duits"),
    219: ("DK", "Deens"),
    220: ("DK", "Deens"),
    224: ("ES", "Spaans"),
    225: ("ES", "Spaans"),
    226: ("FR", "Frans"),
    227: ("FR", "Frans"),
    228: ("FR", "Frans"),
    229: ("MT", "Maltees"),
    230: ("FI", "Fins"),
    231: ("FO", "Faroe Is"),
    232: ("GB", "Engels"),
    233: ("GB", "Engels"),
    234: ("GB", "Engels"),
    235: ("GB", "Engels"),
    236: ("GI", "Gibraltar"),
    237: ("GR", "Grieks"),
    238: ("HR", "Croatia"),
    239: ("GR", "Grieks"),
    240: ("GR", "Grieks"),
    241: ("GR", "Grieks"),
    242: ("MA", "Morokaans"),
    243: ("HU", "Hongaars"),
    244: ("NL", "Nederlands"),
    245: ("NL", "Nederlands"),
    246: ("NL", "Nederlands"),
    247: ("IT", "Italiaans"),
    248: ("MT", "Maltees"),
    249: ("MT", "Maltees"),
    250: ("IE", "Iers"),
    251: ("IS", "Iislands"),
    252: ("LI", "Liechtenstein"),
    253: ("LU", "Luxembourg"),
    254: ("MC", "Monagaskisch"),
    255: ("PT", "Portugees"),
    256: ("MT", "Maltees"),
    257: ("NO", "Noors"),
    258: ("NO", "Noors"),
    259: ("NO", "Noors"),
    261: ("PL", "Pools"),
    262: ("ME", "Montenegro"),
    263: ("PT", "Portugees"),
    264: ("RO", "Roemeens"),
    265: ("SE", "Zweeds"),
    266: ("SE", "Zweeds"),
    267: ("SK", "Slovakia"),
    268: ("SM", "San Marino"),
    269: ("CH", "Switsers"),
    270: ("CZ", "Tjechisch"),
    271: ("TR", "Turks"),
    272: ("UA", "Ukrains"),
    273: ("RU", "Russisch"),
    274: ("MK", "FYR Macedonia"),
    275: ("LV", "Latvia"),
    276: ("EE", "Estonia"),
    277: ("LT", "Lithuania"),
    278: ("SI", "Slovenia"),
    279: ("RS", "Serbia"),
    301: ("AI", "Anguilla"),
    303: ("US", "amerikaans"),
    304: ("AG", "Antigua Barbuda"),
    305: ("AG", "Antigua Barbuda"),
    306: ("CW", "Curacao"),
    307: ("AW", "Aruba"),
    308: ("BS", "Bahamas"),
    309: ("BS", "Bahamas"),
    310: ("BM", "Bermuda"),
    311: ("BS", "Bahamas"),
    312: ("BZ", "Belize"),
    314: ("BB", "Barbados"),
    316: ("CA", "Canada"),
    319: ("KY", "Cayman Is"),
    321: ("CR", "Costa Rica"),
    323: ("CU", "Cuba"),
    325: ("DM", "Dominica"),
    327: ("DO", "Dominican Rep"),
    329: ("GP", "Guadeloupe"),
    330: ("GD", "Grenada"),
    331: ("GL", "Groenlands"),
    332: ("GT", "Guatemala"),
    334: ("HN", "Hondurees"),
    336: ("HT", "Haitiaans"),
    338: ("US", "Amerikaans"),
    339: ("JM", "Jamaica"),
    341: ("KN", "St Kitts Nevis"),
    343: ("LC", "St Lucia"),
    345: ("MX", "Mexicaans"),
    347: ("MQ", "Martinique"),
    348: ("MS", "Montserrat"),
    350: ("NI", "Nicaragua"),
    351: ("PA", "Panamees"),
    352: ("PA", "Panamees"),
    353: ("PA", "Panamees"),
    354: ("PA", "Panamees"),
    355: ("PA", "Panamees"),
    356: ("PA", "Panamees"),
    357: ("PA", "Panamees"),
    358: ("PR", "Puerto Rico"),
    359: ("SV", "El Salvador"),
    361: ("PM", "St Pierre Miquelon"),
    362: ("TT", "Trinidad Tobago"),
    364: ("TC", "Turks Caicos Is"),
    366: ("US", "Amerikaans"),
    367: ("US", "Amerikaans"),
    368: ("US", "Amerikaans"),
    369: ("US", "Amerikaans"),
    370: ("PA", "Panamees"),
    371: ("PA", "Panamees"),
    372: ("PA", "Panamees"),
    373: ("PA", "Panamees"),
    374: ("PA", "Panamees"),
    375: ("VC", "St Vincent Grenadines"),
    376: ("VC", "St Vincent Grenadines"),
    377: ("VC", "St Vincent Grenadines"),
    378: ("VG", "British Virgin Is"),
    379: ("VI", "US Virgin Is"),
    401: ("AF", "Afghanistan"),
    403: ("SA", "Saudi Arabia"),
    405: ("BD", "Bangladesh"),
    408: ("BH", "Bahrain"),
    410: ("BT", "Bhutan"),
    412: ("CN", "Chinees"),
    413: ("CN", "Chineesa"),
    414: ("CN", "Chinees"),
    416: ("TW", "Taiwanees"),
    417: ("LK", "Sri Lanka"),
    419: ("IN", "India"),
    422: ("IR", "Iran"),
    423: ("AZ", "Azerbaijan"),
    425: ("IQ", "Iraq"),
    428: ("IL", "Israel"),
    431: ("JP", "Japans"),
    432: ("JP", "Japans"),
    434: ("TM", "Turkmenistan"),
    436: ("KZ", "Kazakhstan"),
    437: ("UZ", "Uzbekistan"),
    438: ("JO", "Jordan"),
    440: ("KR", "Koreaans"),
    441: ("KR", "Koreaans"),
    443: ("PS", "Palestine"),
    445: ("KP", "DPR Korea"),
    447: ("KW", "Kuwait"),
    450: ("LB", "Lebanon"),
    451: ("KG", "Kyrgyz Republic"),
    453: ("MO", "Macao"),
    455: ("MV", "Maldives"),
    457: ("MN", "Mongolia"),
    459: ("NP", "Nepal"),
    461: ("OM", "Oman"),
    463: ("PK", "Pakistan"),
    466: ("QA", "Qatar"),
    468: ("SY", "Syria"),
    470: ("AE", "UAE"),
    471: ("AE", "UAE"),
    472: ("TJ", "Tajikistan"),
    473: ("YE", "Yemen"),
    475: ("YE", "Yemen"),
    477: ("HK", "Hong Kong"),
    478: ("BA", "Bosnia and Herzegovina"),
    501: ("AQ", "Antarctica"),
    503: ("AU", "Australia"),
    506: ("MM", "Myanmar"),
    508: ("BN", "Brunei"),
    510: ("FM", "Micronesia"),
    511: ("PW", "Palau"),
    512: ("NZ", "New Zealand"),
    514: ("KH", "Cambodia"),
    515: ("KH", "Cambodia"),
    516: ("CX", "Christmas Is"),
    518: ("CK", "Cook Is"),
    520: ("FJ", "Fiji"),
    523: ("CC", "Cocos Is"),
    525: ("ID", "Indonesia"),
    529: ("KI", "Kiribati"),
    531: ("LA", "Laos"),
    533: ("MY", "Malaysia"),
    536: ("MP", "N Mariana Is"),
    538: ("MH", "Marshall Is"),
    540: ("NC", "New Caledonia"),
    542: ("NU", "Niue"),
    544: ("NR", "Nauru"),
    546: ("PF", "French Polynesia"),
    548: ("PH", "Philippines"),
    553: ("PG", "Papua New Guinea"),
    555: ("PN", "Pitcairn Is"),
    557: ("SB", "Solomon Is"),
    559: ("AS", "American Samoa"),
    561: ("WS", "Samoa"),
    563: ("SG", "Singapore"),
    564: ("SG", "Singapore"),
    565: ("SG", "Singapore"),
    566: ("SG", "Singapore"),
    567: ("TH", "Thailand"),
    570: ("TO", "Tonga"),
    572: ("TV", "Tuvalu"),
    574: ("VN", "Vietnam"),
    576: ("VU", "Vanuatu"),
    577: ("VU", "Vanuatu"),
    578: ("WF", "Wallis Futuna Is"),
    601: ("ZA", "South Africa"),
    603: ("AO", "Angola"),
    605: ("DZ", "Algeria"),
    607: ("TF", "St Paul Amsterdam Is"),
    608: ("IO", "Ascension Is"),
    609: ("BI", "Burundi"),
    610: ("BJ", "Benin"),
    611: ("BW", "Botswana"),
    612: ("CF", "Cen Afr Rep"),
    613: ("CM", "Cameroon"),
    615: ("CG", "Congo"),
    616: ("KM", "Comoros"),
    617: ("CV", "Cape Verde"),
    618: ("AQ", "Antarctica"),
    619: ("CI", "Ivory Coast"),
    620: ("KM", "Comoros"),
    621: ("DJ", "Djibouti"),
    622: ("EG", "Egypt"),
    624: ("ET", "Ethiopia"),
    625: ("ER", "Eritrea"),
    626: ("GA", "Gabon"),
    627: ("GH", "Ghana"),
    629: ("GM", "Gambia"),
    630: ("GW", "Guinea-Bissau"),
    631: ("GQ", "Equ. Guinea"),
    632: ("GN", "Guinea"),
    633: ("BF", "Burkina Faso"),
    634: ("KE", "Kenya"),
    635: ("AQ", "Antarctica"),
    636: ("LR", "Liberia"),
    637: ("LR", "Liberia"),
    642: ("LY", "Libya"),
    644: ("LS", "Lesotho"),
    645: ("MU", "Mauritius"),
    647: ("MG", "Madagascar"),
    649: ("ML", "Mali"),
    650: ("MZ", "Mozambique"),
    654: ("MR", "Mauritania"),
    655: ("MW", "Malawi"),
    656: ("NE", "Niger"),
    657: ("NG", "Nigeria"),
    659: ("NA", "Namibia"),
    660: ("RE", "Reunion"),
    661: ("RW", "Rwanda"),
    662: ("SD", "Sudan"),
    663: ("SN", "Senegal"),
    664: ("SC", "Seychelles"),
    665: ("SH", "St Helena"),
    666: ("SO", "Somalia"),
    667: ("SL", "Sierra Leone"),
    668: ("ST", "Sao Tome Principe"),
    669: ("SZ", "Swaziland"),
    670: ("TD", "Chad"),
    671: ("TG", "Togo"),
    672: ("TN", "Tunisia"),
    674: ("TZ", "Tanzania"),
    675: ("UG", "Uganda"),
    676: ("CD", "DR Congo"),
    677: ("TZ", "Tanzania"),
    678: ("ZM", "Zambia"),
    679: ("ZW", "Zimbabwe"),
    701: ("AR", "Argentina"),
    710: ("BR", "Brazil"),
    720: ("BO", "Bolivia"),
    725: ("CL", "Chile"),
    730: ("CO", "Colombia"),
    735: ("EC", "Ecuador"),
    740: ("UK", "UK"),
    745: ("GF", "Guiana"),
    750: ("GY", "Guyana"),
    755: ("PY", "Paraguay"),
    760: ("PE", "Peru"),
    765: ("SR", "Suriname"),
    770: ("UY", "Uruguay"),
    775: ("VE", "Venezuela"),
}

def get_first_three_digits(num: int) -> int:
    if num < 1000:
        return num
    digits = int(math.log10(num)) + 1
    return int(num // (10**(digits - 3)))


def get_country(mmsi: int) -> typing.Tuple[str, str]:
    return COUNTRY_MAPPING.get(get_first_three_digits(mmsi), ('NA', 'Unknown'))


if __name__ == "__main__":
	print(get_country(244030153))


