"""
ships nationality
"""
import typing
import math

COUNTRY_MAPPING = {
    201: ("AL", "Albanees"),
    202: ("AD", "Andorrees"),
    203: ("AT", "Oostenrijker"),
    204: ("PT", "Portugees"),
    205: ("BE", "Belg"),
    206: ("BY", "Belarus"),
    207: ("BG", "Bulgaar"),
    208: ("VA", "Vaticaans"),
    209: ("CY", "Cyprioot"),
    210: ("CY", "Cyprioot   "),
    211: ("DE", "Duitser"),
    212: ("CY", "Cyprioot"),
    213: ("GE", "Georgier"),
    214: ("MD", "Moldavier"),
    215: ("MT", "Maltees"),
    216: ("AM", "Armeneen"),
    218: ("DE", "Duitser"),
    219: ("DK", "Deen"),
    220: ("DK", "Deen"),
    224: ("ES", "Spanjaard"),
    225: ("ES", "Spanjaard"),
    226: ("FR", "Fransman"),
    227: ("FR", "Fransman"),
    228: ("FR", "Fransman"),
    229: ("MT", "Maltees"),
    230: ("FI", "Fin"),
    231: ("FO", "Faeröer"),
    232: ("GB", "Engelsman"),
    233: ("GB", "Engelsman"),
    234: ("GB", "Engelsman"),
    235: ("GB", "Engelsman"),
    236: ("GI", "Gibraltarees"),
    237: ("GR", "Griek"),
    238: ("HR", "Kroaat"),
    239: ("GR", "Griek"),
    240: ("GR", "Griek"),
    241: ("GR", "Griek"),
    242: ("MA", "Morokaan"),
    243: ("HU", "Hongaar"),
    244: ("NL", "Nederlander"),
    245: ("NL", "Nederlander"),
    246: ("NL", "Nederlander"),
    247: ("IT", "Italiaan"),
    248: ("MT", "Maltees"),
    249: ("MT", "Maltees"),
    250: ("IE", "Ier"),
    251: ("IS", "IJslander"),
    252: ("LI", "Liechtensteiner"),
    253: ("LU", "Luxemburger"),
    254: ("MC", "Monagaskisch"),
    255: ("PT", "Portugees"),
    256: ("MT", "Maltees"),
    257: ("NO", "Noor"),
    258: ("NO", "Noor"),
    259: ("NO", "Noor"),
    261: ("PL", "Pool"),
    262: ("ME", "Montenegro"),
    263: ("PT", "Portugees"),
    264: ("RO", "Roemeen"),
    265: ("SE", "Zweed"),
    266: ("SE", "Zweed"),
    267: ("SK", "Slovakees"),
    268: ("SM", "San Marinees"),
    269: ("CH", "Zwitser"),
    270: ("CZ", "Tjech"),
    271: ("TR", "Turk"),
    272: ("UA", "Ukrainer"),
    273: ("RU", "Rus"),
    274: ("MK", "Macedonier"),
    275: ("LV", "Let"),
    276: ("EE", "Est"),
    277: ("LT", "Litouwer"),
    278: ("SI", "Sloveen"),
    279: ("RS", "Serviër"),
    301: ("AI", "Anguillaan"),
    303: ("US", "Amerikaan"),
    304: ("AG", "Antiguaan en Barbudaan"),
    305: ("AG", "Antiguaan en Barbudaan"),
    306: ("CW", "Curaçaoenaar"),
    307: ("AW", "Arubaan"),
    308: ("BS", "Bahamaan"),
    309: ("BS", "Bahamaan"),
    310: ("BM", "Bermudaan"),
    311: ("BS", "Bahamaan"),
    312: ("BZ", "Belizaan"),
    314: ("BB", "Barbadiaan"),
    316: ("CA", "Canadees"),
    319: ("KY", "Caymaniaan"),
    321: ("CR", "Costa Ricaan"),
    323: ("CU", "Cubaan"),
    325: ("DM", "Dominicaan"),
    327: ("DO", "Dominicaanse Republiek"),
    329: ("GP", "Guadeloupeer"),
    330: ("GD", "Grenadiaan"),
    331: ("GL", "Groenlander"),
    332: ("GT", "Guatemalteek"),
    334: ("HN", "Hondurees"),
    336: ("HT", "Haitiaan"),
    338: ("US", "Amerikaan"),
    339: ("JM", "Jamaicaan"),
    341: ("KN", "St Kitts Nevis"),
    343: ("LC", "St Luciaan    "),
    345: ("MX", "Mexicaan"),
    347: ("MQ", "Martiniquees"),
    348: ("MS", "Montserrat"),
    350: ("NI", "Nicaragua"),
    351: ("PA", "Panamees"),
    352: ("PA", "Panamees"),
    353: ("PA", "Panamees"),
    354: ("PA", "Panamees"),
    355: ("PA", "Panamees"),
    356: ("PA", "Panamees"),
    357: ("PA", "Panamees"),
    358: ("PR", "Puerto Ricaan"),
    359: ("SV", "El Salvadoraan"),
    361: ("PM", "St Pierre Miquelon"),
    362: ("TT", "Trinidads"),
    364: ("TC", "Turks Caicos Is"),
    366: ("US", "Amerikaan"),
    367: ("US", "Amerikaan"),
    368: ("US", "Amerikaan"),
    369: ("US", "Amerikaan"),
    370: ("PA", "Panamees"),
    371: ("PA", "Panamees"),
    372: ("PA", "Panamees"),
    373: ("PA", "Panamees"),
    374: ("PA", "Panamees"),
    375: ("VC", "St Vincent Grenadinees"),
    376: ("VC", "St Vincent Grenadinees"),
    377: ("VC", "St Vincent Grenadinees"),
    378: ("VG", "British Virgin Is"),
    379: ("VI", "US Virgin Is"),
    401: ("AF", "Afghaan"),
    403: ("SA", "Saudi Arabisch"),
    405: ("BD", "Bangladees"),
    408: ("BH", "Bahrains"),
    410: ("BT", "Bhutans"),
    412: ("CN", "Chinees"),
    413: ("CN", "Chinees"),
    414: ("CN", "Chinees"),
    416: ("TW", "Taiwanees"),
    417: ("LK", "Sri Lankaans"),
    419: ("IN", "Indier"),
    422: ("IR", "Iraan"),
    423: ("AZ", "Azerbajaan"),
    425: ("IQ", "Iraqi"),
    428: ("IL", "Israelier"),
    431: ("JP", "Japanner"),
    432: ("JP", "Japanner"),
    434: ("TM", "Turkmenistaan"),
    436: ("KZ", "Kazachstaan"),
    437: ("UZ", "Uzbekistaan"),
    438: ("JO", "Jordaanier"),
    440: ("KR", "Koreaan"),
    441: ("KR", "Koreaan"),
    443: ("PS", "Palestijn"),
    445: ("KP", "DPR Koreaan"),
    447: ("KW", "Koeweits"),
    450: ("LB", "Libanees"),
    451: ("KG", "Kyrgyz Republic"),
    453: ("MO", "Macaus"),
    455: ("MV", "Maledivisch"),
    457: ("MN", "Mongolees"),
    459: ("NP", "Nepalees"),
    461: ("OM", "Omanees"),
    463: ("PK", "Pakistaan"),
    466: ("QA", "Qatarees"),
    468: ("SY", "Syrier"),
    470: ("AE", "UAE"),
    471: ("AE", "UAE"),
    472: ("TJ", "Tajikistaan"),
    473: ("YE", "Jemeniet"),
    475: ("YE", "Jemeniet"),
    477: ("HK", "HongKong"),
    478: ("BA", "Bosnia and Herzegovinees"),
    501: ("AQ", "Antarctisch"),
    503: ("AU", "Australisch"),
    506: ("MM", "Myanmarees"),
    508: ("BN", "Brunees"),
    510: ("FM", "Micronesisch"),
    511: ("PW", "Palaus"),
    512: ("NZ", "New Zealander"),
    514: ("KH", "Cambodiaan"),
    515: ("KH", "Cambodiaan"),
    516: ("CX", "Christmas Is"),
    518: ("CK", "Cook Is"),
    520: ("FJ", "Fijisch"),
    523: ("CC", "Cocos Is"),
    525: ("ID", "Indonesier"),
    529: ("KI", "Kiribatisch"),
    531: ("LA", "Laotiaan"),
    533: ("MY", "Maleier"),
    536: ("MP", "N Mariana Is"),
    538: ("MH", "Marshall Is"),
    540: ("NC", "New Caledonia"),
    542: ("NU", "Niuaans"),
    544: ("NR", "Nauruaan"),
    546: ("PF", "French Polynesisch"),
    548: ("PH", "Philipijn"),
    553: ("PG", "Papua New Guinees"),
    555: ("PN", "Pitcairn Is"),
    557: ("SB", "Solomon Is"),
    559: ("AS", "American Samoa"),
    561: ("WS", "Samoaans"),
    563: ("SG", "Singaporees"),
    564: ("SG", "Singaporees"),
    565: ("SG", "Singaporees"),
    566: ("SG", "Singaporees"),
    567: ("TH", "Thai"),
    570: ("TO", "Tongaan"),
    572: ("TV", "Tuvalaan"),
    574: ("VN", "Vietnamees"),
    576: ("VU", "Vanuataans"),
    577: ("VU", "Vanuataans"),
    578: ("WF", "Wallis Futuna Is"),
    601: ("ZA", "Zuid Afrikaan"),
    603: ("AO", "Angolees"),
    605: ("DZ", "Algerijn"),
    607: ("TF", "St Paul Amsterdam Is"),
    608: ("IO", "Ascension Is"),
    609: ("BI", "Burundees"),
    610: ("BJ", "Benins"),
    611: ("BW", "Botswaans"),
    612: ("CF", "Cen Afr Rep"),
    613: ("CM", "Cameroons"),
    615: ("CG", "Congolees"),
    616: ("KM", "Comorees"),
    617: ("CV", "Cape Verdisch"),
    618: ("AQ", "Antarctica"),
    619: ("CI", "Ivory Coasts"),
    620: ("KM", "Comoros"),
    621: ("DJ", "Djibouti"),
    622: ("EG", "Egyptisch"),
    624: ("ET", "Ethiopisch"),
    625: ("ER", "Eritreer"),
    626: ("GA", "Gabonees"),
    627: ("GH", "Ghanees"),
    629: ("GM", "Gambiaan"),
    630: ("GW", "Guinea-Bissau"),
    631: ("GQ", "Equ. Guinees"),
    632: ("GN", "Guinees"),
    633: ("BF", "Burkina Faso"),
    634: ("KE", "Keniaan"),
    635: ("AQ", "Antarctisch"),
    636: ("LR", "Liberiaan"),
    637: ("LR", "Liberiaan"),
    642: ("LY", "Libier"),
    644: ("LS", "Lesotho"),
    645: ("MU", "Mauritaan"),
    647: ("MG", "Madagaskisch"),
    649: ("ML", "Malinees"),
    650: ("MZ", "Mozambique"),
    654: ("MR", "Mauritaan"),
    655: ("MW", "Malawees"),
    656: ("NE", "Nigeriaan"),
    657: ("NG", "Nigeriaan"),
    659: ("NA", "Namibier"),
    660: ("RE", "Reunion"),
    661: ("RW", "Rwandees"),
    662: ("SD", "Sudanees"),
    663: ("SN", "Senegalees"),
    664: ("SC", "Seychelles"),
    665: ("SH", "St Helena"),
    666: ("SO", "Somalia"),
    667: ("SL", "Sierra Leone"),
    668: ("ST", "Sao Tome Principe"),
    669: ("SZ", "Swaziland"),
    670: ("TD", "Chad"),
    671: ("TG", "Togo"),
    672: ("TN", "Tunisisch"),
    674: ("TZ", "Tanzania"),
    675: ("UG", "Ugandees"),
    676: ("CD", "DR Congo"),
    677: ("TZ", "Tanzania"),
    678: ("ZM", "Zambiaans"),
    679: ("ZW", "Zimbabwe"),
    701: ("AR", "Argentijn"),
    710: ("BR", "Braziliaan"),
    720: ("BO", "Bolivia"),
    725: ("CL", "Chileen"),
    730: ("CO", "Colombiaan"),
    735: ("EC", "Ecuadoriaan"),
    740: ("UK", "Engelsman"),
    745: ("GF", "Guianaan"),
    750: ("GY", "Guyaan"),
    755: ("PY", "Paraguayaan"),
    760: ("PE", "Peruaan"),
    765: ("SR", "Surinamer"),
    770: ("UY", "Uruguayaan"),
    775: ("VE", "Venezolaan"),
}

def get_first_three_digits(num: int) -> int:
    if num < 1000:
        return num
    digits = int(math.log10(num)) + 1
    return int(num // (10**(digits - 3)))


def get_country(mmsi: int) -> typing.Tuple[str, str]:
    return COUNTRY_MAPPING.get(get_first_three_digits(mmsi), ('NA', 'Unknown'))


if __name__ == "__main__":
	print(get_country(244030153))


