"""
ships nationality
"""
import typing
import math

COUNTRY_MAPPING = {
    201: ("AL", "Albanees"),
    202: ("AD", "Andorrees"),
    203: ("AT", "Oostenrijks"),
    204: ("PT", "Portugees"),
    205: ("BE", "Belgisch"),
    206: ("BY", "Belarusisch"),
    207: ("BG", "Bulgaars"),
    208: ("VA", "Vaticaans"),
    209: ("CY", "Cypriotisch"),
    210: ("CY", "Cypriotisch"),
    211: ("DE", "Duits"),
    212: ("CY", "Cypriotisch"),
    213: ("GE", "Georgisch"),
    214: ("MD", "Moldavisch"),
    215: ("MT", "Maltees"),
    216: ("AM", "Armeneens"),
    218: ("DE", "Duits"),
    219: ("DK", "Deens"),
    220: ("DK", "Deens"),
    224: ("ES", "Spaans"),
    225: ("ES", "Spaans"),
    226: ("FR", "Frans"),
    227: ("FR", "Frans"),
    228: ("FR", "Frans"),
    229: ("MT", "Maltees"),
    230: ("FI", "Fins"),
    231: ("FO", "Faeröers"),
    232: ("GB", "Engels"),
    233: ("GB", "Engels"),
    234: ("GB", "Engels"),
    235: ("GB", "Engels"),
    236: ("GI", "Gibraltarees"),
    237: ("GR", "Grieks"),
    238: ("HR", "Kroatisch"),
    239: ("GR", "Grieks"),
    240: ("GR", "Grieks"),
    241: ("GR", "Grieks"),
    242: ("MA", "Morokaans"),
    243: ("HU", "Hongaars"),
    244: ("NL", "Nederlands"),
    245: ("NL", "Nederlands"),
    246: ("NL", "Nederlands"),
    247: ("IT", "Italiaans"),
    248: ("MT", "Maltees"),
    249: ("MT", "Maltees"),
    250: ("IE", "Iers"),
    251: ("IS", "IJslands"),
    252: ("LI", "Liechtensteins"),
    253: ("LU", "Luxemburgisch"),
    254: ("MC", "Monagaskisch"),
    255: ("PT", "Portugees"),
    256: ("MT", "Maltees"),
    257: ("NO", "Noors"),
    258: ("NO", "Noors"),
    259: ("NO", "Noors"),
    261: ("PL", "Pools"),
    262: ("ME", "Montenegro"),
    263: ("PT", "Portugees"),
    264: ("RO", "Roemeens"),
    265: ("SE", "Zweeds"),
    266: ("SE", "Zweeds"),
    267: ("SK", "Slovakees"),
    268: ("SM", "San Marinees"),
    269: ("CH", "Zwitsers"),
    270: ("CZ", "Tjechisch"),
    271: ("TR", "Turks"),
    272: ("UA", "Ukrains"),
    273: ("RU", "Russisch"),
    274: ("MK", "Macedonisch"),
    275: ("LV", "Lets"),
    276: ("EE", "Ests"),
    277: ("LT", "Litouws"),
    278: ("SI", "Sloveens"),
    279: ("RS", "Servisch"),
    301: ("AI", "Anguillaans"),
    303: ("US", "Amerikaans"),
    304: ("AG", "Antiguaans en Barbudaans"),
    305: ("AG", "Antiguaans en Barbudaans"),
    306: ("CW", "Curaçaos"),
    307: ("AW", "Arubaans"),
    308: ("BS", "Bahamas"),
    309: ("BS", "Bahamas"),
    310: ("BM", "Bermuda"),
    311: ("BS", "Bahamas"),
    312: ("BZ", "Belizaans"),
    314: ("BB", "Barbadiaans"),
    316: ("CA", "Canadees"),
    319: ("KY", "Caymaniaans"),
    321: ("CR", "Costa Ricaans"),
    323: ("CU", "Cubaans"),
    325: ("DM", "Dominicaans"),
    327: ("DO", "Dominican Rep"),
    329: ("GP", "Guadeloupe"),
    330: ("GD", "Grenadees"),
    331: ("GL", "Groenlands"),
    332: ("GT", "Guatemalaans"),
    334: ("HN", "Hondurees"),
    336: ("HT", "Haitiaans"),
    338: ("US", "Amerikaans"),
    339: ("JM", "Jamaicaans"),
    341: ("KN", "St Kitts Nevis"),
    343: ("LC", "St Luciaans    "),
    345: ("MX", "Mexicaans"),
    347: ("MQ", "Martinique"),
    348: ("MS", "Montserrat"),
    350: ("NI", "Nicaragua"),
    351: ("PA", "Panamees"),
    352: ("PA", "Panamees"),
    353: ("PA", "Panamees"),
    354: ("PA", "Panamees"),
    355: ("PA", "Panamees"),
    356: ("PA", "Panamees"),
    357: ("PA", "Panamees"),
    358: ("PR", "Puerto Ricaans"),
    359: ("SV", "El Salvadoraans"),
    361: ("PM", "St Pierre Miquelons"),
    362: ("TT", "Trinidads"),
    364: ("TC", "Turks Caicos Is"),
    366: ("US", "Amerikaans"),
    367: ("US", "Amerikaans"),
    368: ("US", "Amerikaans"),
    369: ("US", "Amerikaans"),
    370: ("PA", "Panamees"),
    371: ("PA", "Panamees"),
    372: ("PA", "Panamees"),
    373: ("PA", "Panamees"),
    374: ("PA", "Panamees"),
    375: ("VC", "St Vincent Grenadinees"),
    376: ("VC", "St Vincent Grenadinees"),
    377: ("VC", "St Vincent Grenadinees"),
    378: ("VG", "British Virgin Is"),
    379: ("VI", "US Virgin Is"),
    401: ("AF", "Afghaans"),
    403: ("SA", "Saudi Arabisch"),
    405: ("BD", "Bangladees"),
    408: ("BH", "Bahrains"),
    410: ("BT", "Bhutans"),
    412: ("CN", "Chinees"),
    413: ("CN", "Chinees"),
    414: ("CN", "Chinees"),
    416: ("TW", "Taiwanees"),
    417: ("LK", "Sri Lankaans"),
    419: ("IN", "Indiaas"),
    422: ("IR", "Iraans"),
    423: ("AZ", "Azerbajaans"),
    425: ("IQ", "Iraqees"),
    428: ("IL", "Israelisch"),
    431: ("JP", "Japans"),
    432: ("JP", "Japans"),
    434: ("TM", "Turkmenistaans"),
    436: ("KZ", "Kazakhstaans"),
    437: ("UZ", "Uzbekistaans"),
    438: ("JO", "Jordaans"),
    440: ("KR", "Koreaans"),
    441: ("KR", "Koreaans"),
    443: ("PS", "Palestijns"),
    445: ("KP", "DPR Koreaans"),
    447: ("KW", "Koeweits"),
    450: ("LB", "Libanees"),
    451: ("KG", "Kyrgyz Republic"),
    453: ("MO", "Macaus"),
    455: ("MV", "Maledivisch"),
    457: ("MN", "Mongolees"),
    459: ("NP", "Nepalees"),
    461: ("OM", "Omanees"),
    463: ("PK", "Pakistaans"),
    466: ("QA", "Qatarees"),
    468: ("SY", "Syrisch"),
    470: ("AE", "UAE"),
    471: ("AE", "UAE"),
    472: ("TJ", "Tajikistaans"),
    473: ("YE", "Jemenitisch"),
    475: ("YE", "Jemenitisch"),
    477: ("HK", "HongKongs"),
    478: ("BA", "Bosnia and Herzegovinees"),
    501: ("AQ", "Antarctisch"),
    503: ("AU", "Australisch"),
    506: ("MM", "Myanmarees"),
    508: ("BN", "Brunees"),
    510: ("FM", "Micronesisch"),
    511: ("PW", "Palaus"),
    512: ("NZ", "New Zealands"),
    514: ("KH", "Cambodiaans"),
    515: ("KH", "Cambodiaans"),
    516: ("CX", "Christmas Is"),
    518: ("CK", "Cook Is"),
    520: ("FJ", "Fijisch"),
    523: ("CC", "Cocos Is"),
    525: ("ID", "Indonesisch"),
    529: ("KI", "Kiribatisch"),
    531: ("LA", "Laotiaans"),
    533: ("MY", "Malaysisch"),
    536: ("MP", "N Mariana Is"),
    538: ("MH", "Marshall Is"),
    540: ("NC", "New Caledonia"),
    542: ("NU", "Niuaans"),
    544: ("NR", "Nauruaan"),
    546: ("PF", "French Polynesisch"),
    548: ("PH", "Philipijns"),
    553: ("PG", "Papua New Guinees"),
    555: ("PN", "Pitcairn Is"),
    557: ("SB", "Solomon Is"),
    559: ("AS", "American Samoa"),
    561: ("WS", "Samoaans"),
    563: ("SG", "Singaporees"),
    564: ("SG", "Singaporees"),
    565: ("SG", "Singaporees"),
    566: ("SG", "Singaporees"),
    567: ("TH", "Thais"),
    570: ("TO", "Tongaans"),
    572: ("TV", "Tuvalaans"),
    574: ("VN", "Vietnamees"),
    576: ("VU", "Vanuataans"),
    577: ("VU", "Vanuataans"),
    578: ("WF", "Wallis Futuna Is"),
    601: ("ZA", "Zuid Afrikaans"),
    603: ("AO", "Angolees"),
    605: ("DZ", "Algerijns"),
    607: ("TF", "St Paul Amsterdam Is"),
    608: ("IO", "Ascension Is"),
    609: ("BI", "Burundees"),
    610: ("BJ", "Benins"),
    611: ("BW", "Botswaans"),
    612: ("CF", "Cen Afr Rep"),
    613: ("CM", "Cameroons"),
    615: ("CG", "Congolees"),
    616: ("KM", "Comorees"),
    617: ("CV", "Cape Verdisch"),
    618: ("AQ", "Antarctica"),
    619: ("CI", "Ivory Coasts"),
    620: ("KM", "Comoros"),
    621: ("DJ", "Djibouti"),
    622: ("EG", "Egyptisch"),
    624: ("ET", "Ethiopisch"),
    625: ("ER", "Eritrees"),
    626: ("GA", "Gabonees"),
    627: ("GH", "Ghanees"),
    629: ("GM", "Gambiaans"),
    630: ("GW", "Guinea-Bissau"),
    631: ("GQ", "Equ. Guinees"),
    632: ("GN", "Guinees"),
    633: ("BF", "Burkina Faso"),
    634: ("KE", "Keniaans"),
    635: ("AQ", "Antarctisch"),
    636: ("LR", "Liberiaans"),
    637: ("LR", "Liberiaans"),
    642: ("LY", "Libisch"),
    644: ("LS", "Lesotho"),
    645: ("MU", "Mauritaans"),
    647: ("MG", "Madagaskisch"),
    649: ("ML", "Mali"),
    650: ("MZ", "Mozambique"),
    654: ("MR", "Mauritaans"),
    655: ("MW", "Malawees"),
    656: ("NE", "Niger"),
    657: ("NG", "Nigeriaans"),
    659: ("NA", "Namibisch"),
    660: ("RE", "Reunion"),
    661: ("RW", "Rwandees"),
    662: ("SD", "Sudanees"),
    663: ("SN", "Senegalees"),
    664: ("SC", "Seychelles"),
    665: ("SH", "St Helena"),
    666: ("SO", "Somalia"),
    667: ("SL", "Sierra Leone"),
    668: ("ST", "Sao Tome Principe"),
    669: ("SZ", "Swaziland"),
    670: ("TD", "Chad"),
    671: ("TG", "Togo"),
    672: ("TN", "Tunisisch"),
    674: ("TZ", "Tanzania"),
    675: ("UG", "Ugandees"),
    676: ("CD", "DR Congo"),
    677: ("TZ", "Tanzania"),
    678: ("ZM", "Zambiaans"),
    679: ("ZW", "Zimbabwe"),
    701: ("AR", "Argentijns"),
    710: ("BR", "Braziliaans"),
    720: ("BO", "Bolivia"),
    725: ("CL", "Chileens"),
    730: ("CO", "Colombia"),
    735: ("EC", "Ecuador"),
    740: ("UK", "Engels"),
    745: ("GF", "Guiana"),
    750: ("GY", "Guyana"),
    755: ("PY", "Paraguay"),
    760: ("PE", "Peru"),
    765: ("SR", "Surinaams"),
    770: ("UY", "Uruguay"),
    775: ("VE", "Venezuelaans"),
}

def get_first_three_digits(num: int) -> int:
    if num < 1000:
        return num
    digits = int(math.log10(num)) + 1
    return int(num // (10**(digits - 3)))


def get_country(mmsi: int) -> typing.Tuple[str, str]:
    return COUNTRY_MAPPING.get(get_first_three_digits(mmsi), ('NA', 'Unknown'))


if __name__ == "__main__":
	print(get_country(244030153))


