""" create shiptypes list """

def shiptype(t : int):
    """ return ship type description for type t """
    if t is None:
        return "Unknown"
    ship_type =	{
                0 :  "Not available",
                1 :  "Reserved for future use",
                2 :  "Reserved for future use",
                3 :  "Reserved for future use",
                4 :  "Reserved for future use",
                5 :  "Reserved for future use",
                6 :  "Reserved for future use",
                7 :  "Reserved for future use",
                8 :  "Reserved for future use",
                9 :  "Reserved for future use",
                10 :  "Reserved for future use",
                11 :  "Reserved for future use",
                12 :  "Reserved for future use",
                13 :  "Reserved for future use",
                14 :  "Reserved for future use",
                15 :  "Reserved for future use",
                16 :  "Reserved for future use",
                17 :  "Reserved for future use",
                18 :  "Reserved for future use",
                19 :  "Reserved for future use",
                20  :  "laagvlieger", #all ships of this type",
                21  :  "laagvlieger, Hazardous category A",
                22 :  "laagvlieger, Hazardous category B",
                23 :  "laagvlieger, Hazardous category C",
                24 :  "laagvlieger, Hazardous category D",
                25 :  "laagvlieger, Reserved for future use",
                26 :  "laagvlieger, Reserved for future use",
                27 :  "laagvlieger, Reserved for future use",
                28 :  "laagvlieger, Reserved for future use",
                29 :  "laagvlieger, Reserved for future use",
                30 :  "visser",
                31 :  "sleper",
                32 :  "grote sleep: length exceeds 200m or breadth exceeds 25m",
                33 :  "baggeraar",
                34 :  "duiker",
                35 :  "mililitair",
                36 :  "zeilboot",
                37 :  "pleziervaartuig",
                38 :  "gereserveerd",
                39 :  "gereserveerd",
                40 :  "zeer snel vaartuig", #all ships of this type",
                41 :  "zeer snel vaartuig A",
                42 :  "zeer snel vaartuig B",
                43 :  "zeer snel vaartuig C",
                44 :  "zeer snel vaartuig D",
                45 :  "zeer snel vaartuig ",
                46 :  "zeer snel vaartuig ",
                47 :  "zeer snel vaartuig ",
                48 :  "zeer snel vaartuig ",
                49 :  "zeer snel vaartuig", # Geen aanvullende informatie",
                50 :  "loodsboot",
                51 :  "Reddingsvaartuig",
                52 :  "Sleper",
                53 :  "Havenvaartuig",
                54 :  "Anti-vervuilingsapparatuur",
                55 :  "Wetshandhaving",
                56 :  "reserve- lokaal schip",
                57 :  "reserve- lokaal schip",
                58 :  "hospitaal schip",
                59 :  "neutraal schip",
                60 :  "passagier", #all ships of this type",
                61 :  "passagier A",
                62 :  "passagier B",
                63 :  "passagier C",
                64 :  "passagier D",
                65 :  "passagier ",
                66 :  "passagier ",
                67 :  "passagier ",
                68 :  "passagier ",
                69 :  "passagier", #Geen aanvullende informatie",
                70 :  "vrachtvaarder", #, all ships of this type",
                71 :  "vrachtvaarder A",
                72 :  "vrachtvaarder B",
                73 :  "vrachtvaarder C",
                74 :  "vrachtvaarder D",
                75 :  "vrachtvaarder ",
                76 :  "vrachtvaarder ",
                77 :  "vrachtvaarder ",
                78 :  "vrachtvaarder ",
                79 :  "vrachtvaarder", #, Geen aanvullende informatie",
                80 :  "tanker", #all ships of this type",
                81 :  "tanker A",
                82 :  "tanker B",
                83 :  "tanker C",
                84 :  "tanker D",
                85 :  "tanker ",
                86 :  "tanker ",
                87 :  "tanker ",
                88 :  "tanker ",
                89 :  "tanker", #, Geen aanvullende informatie",
                90 :  "overige type", #, all ships of this type",
                91 :  "overige type A",
                92 :  "overige type B",
                93 :  "overige type C",
                94 :  "overige type D",
                95 :  "overige type ",
                96 :  "overige type ",
                97 :  "overige type ",
                98 :  "overige type ",
                99 :  "overige type", #, Geen aanvullende informatie"
            }
    return ship_type[t]

if __name__ == "__main__":
    for i in range(100):
        print(i, ':', shiptype(i))
